### PR TITLE
adds some error handling, cleans up some magic values

### PR DESCRIPTION
**Pull request by ivanchubb**
- remove the `get_directory_path()` function instead relying on a portable `get_cwd()`. if it fails, exit with `-1`
- adds a more portable `PATH_LEN` to act as max path (260) on windows (4096) on linux
- removes a narrowing conversion of the port value in the URL string by using `strtol()` instead of `atoi()`. if out of range, default to the default port.
- slightly reorganizes includes/defines to be grouped.
- handles a case when providing a bad argv[1] results in unknown return value as well as provides a usage print

### CODE REVIEW

**Review by SciLor — APPROVED** [review]

**Review by SciLor — APPROVED** [review]

**Comment by g3gg0** [comment]
thanks for your support.

some of the code was meant to be a temporary solution somewhere inbetween
  "that concept doesn't exist on a platform like ESP32"
and
  "no need to spend time on making this, as this is has to be replaced with something proper".

so for example:
- the cmdline options are win/linux-specific, not meant to be ran bare-metal
- paths and their lengths must not be fixed buffer size - we might have not enough RAM
and for sure a lot other code.

we seem to get to a point where cmdline options are required though.
so switching to getopt might be required soon, having differen entry points of course.

**Comment by g3gg0** [comment]
as you can see, the win32 build failed. can you fix that?
https://github.com/toniebox-reverse-engineering/teddycloud/actions/runs/6372698375/job/17295884511?pr=62

**Comment by ivanchubb** [comment]
i see it failing the checks on some winsock.h parts and main.c:359. could be because i specified `_WIN32` instead of `WIN32`. I did this because [I thought it was best practices](https://groups.google.com/g/fltkcoredev/c/BwKvvtJ_Mog?pli=1). Please correct me if i'm wrong.

**Comment by ivanchubb** [comment]
> some of the code was meant to be a temporary solution somewhere inbetween "that concept doesn't exist on a platform like ESP32" and "no need to spend time on making this, as this is has to be replaced with something proper".

Any suggestions on where I should spend my time helping out? I am still learning this codebase and figured `main.c` was as 
 good a place as any to start.

**Comment by SciLor** [comment]
You may check out the issues with the IDs: 29, 30, 32

https://github.com/toniebox-reverse-engineering/teddycloud/issues/29

Those may help a bit understanding the API

**Comment by g3gg0** [comment]
we also have an issue with the coding style.
the goal is to use snake_case, but as we also use the cyclone lib, lowerCamelCase is widespread.
cleaning up code is also one thing that has to be done.

aside of that, as already written, it might be time to introduce proper commandline option parsing.
i guess some of these options are pure test functions, some might be useful later.

**Comment by g3gg0** [comment]
thanks for your support :)

**Comment by ivanchubb** [comment]
Do you have any standards in terms of documenting what should go in each file? If not, I wouldn't mind helping make that too. It'd help a lot in understanding what is going on and how the code flows, dependencies, etc if I knew where to look for things. I'm not sure if that's typical, but some kind of map, flowchart, or orientation document would be nice. For example, sometimes preprocessor directives look like they are used for error codes (ex: `NO_ERROR`), but other times `0` or `-1`. I saw a common file in `cyclone/common.h`, but I didn't see all error codes defined or an enum type for error codes either.

**Comment by SciLor** [comment]
This sounds great, having a quick start document for people who would like to help to develop teddyCloud with us.

I would suggest using the /wiki/ directoy and md file(s).

cyclone defines all error codes, there is an enum for that.

**Pull request merged**
