### PR TITLE
Add -e flag to echo to allow backslash escapes

### PR DESCRIPTION
**Pull request by manuelm**
Required for terminal colors.

### CODE REVIEW

**Comment by g3gg0** [comment]
for which OS/setup do we need the -e?
with VSCode terminal or Windows Terminal it works fine

**Comment by manuelm** [comment]
Really? Haven't tried VS. Is it still working with `-e`?

Well, every other shell.

from `man echo`:
```
[...]
       If -e is in effect, the following sequences are recognized:
       \\     backslash
[...]
```

**Comment by g3gg0** [comment]
works for bash and is probably shell-dependent.
will check

**Comment by manuelm** [comment]
Colors still working in VSCode here. But I'm running linux. My terminal does not display any colors without the `-e` flag.

**Comment by g3gg0** [comment]
guess, i'll have to change quotation marks too, then?

**Comment by manuelm** [comment]
> guess, i'll have to change quotation marks too, then?

No. Won't help. I assume it depends on the vscode terminal profile.

**Comment by SciLor** [comment]
> > guess, i'll have to change quotation marks too, then?
> 
> No. Won't help. I assume it depends on the vscode terminal profile.

I am also using VSCode under Windows with remote ssh to a Linux machine. 
Colors worked fine.

**Comment by manuelm** [comment]
Working remote colors without `-e`-flag is strange. Something must interpret the escape sequences. Both my terminal client (KDE Konsole) as well as VSCode terminal (bash) currently looks like this:
```
[...]
[ \033[0;32mCC\033[0m   ] \033[0;36msrc/proto/proto/toniebox.pb.freshness-check.fc-request.pb-c.c\033[0m
[ \033[0;32mCC\033[0m   ] \033[0;36msrc/proto/proto/toniebox.pb.freshness-check.fc-response.pb-c.c\033[0m
[ \033[0;32mCC\033[0m   ] \033[0;36msrc/proto/proto/toniebox.pb.rtnl.pb-c.c\033[0m
[ \033[0;32mCC\033[0m   ] \033[0;36msrc/proto/proto/toniebox.pb.taf-header.pb-c.c\033[0m
[ \033[0;33mLINK\033[0m ] \033[0;36mbin/teddycloud\033[0m
```

**Comment by SciLor** [comment]
Do you have the same with teddyCloud itself?

**Comment by manuelm** [comment]
> Do you have the same with teddyCloud itself?

What do you mean by "teddyCloud itself"?. Without the `-e`-flag I see the escape sequences. No colors. `-e` makes the colors work.

Which shell/terminal are you running (`echo $SHELL`)?

**Comment by manuelm** [comment]
Oh now I get it. No teddycloud colors are working fine :-)

**Comment by SciLor** [comment]
its /bin/bash

maybe it is some kind of env variable?

**Comment by manuelm** [comment]
what about using printf instead of echo? e.g. `printf "[ \033[0;36mFOO\033[0m] foo\n"`

**Comment by g3gg0** [comment]
> what about using printf instead of echo? e.g. `printf "[ \033[0;36mFOO\033[0m] foo\n"`

Windows cmd.ex3 shell doesnt have printf

**Comment by manuelm** [comment]
It works but it's not complete. There are still echos with -e missing.

I've pushed an approach which only requires "-e" for the color codes.

**Pull request closed without merging**
